<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0;net9.0-android;net10.0-android</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(TargetFrameworks);net9.0-ios;net10.0-ios;net9.0-maccatalyst;net10.0-maccatalyst</TargetFrameworks>

    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>PowerSync.Common</PackageId>
    <Title>PowerSync.Common</Title>
    <Description>PowerSync.Common is a package that enables local-first and real-time reactive apps with embedded SQLite for .NET clients</Description>
    <Authors>PowerSync</Authors>
    <owners>powersync</owners>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/powersync-ja/powersync-dotnet</RepositoryUrl>
    <PackageProjectUrl>https://powersync.com</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReleaseNotes>https://github.com/powersync-ja/powersync-dotnet/PowerSync/PowerSync.Common/CHANGELOG.md</PackageReleaseNotes>
    <PackageTags>powersync local-first local-storage state-management offline sql db persistence sqlite sync </PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <NoWarn>NU5100;1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <DefaultItemExcludes>$(DefaultItemExcludes);runtimes/**/*.*;</DefaultItemExcludes>
  </PropertyGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="PowerSync.Common.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
  </ItemGroup>

  <!-- For ProjectReference: copy the whole /runtimes/ directory. -->
  <ItemGroup>
    <None Include="runtimes/**/*.*" Pack="true" PackagePath="runtimes/" />
  </ItemGroup>

  <!-- For NuGet-published package: only include the runtime directories for the current target. -->
  <!-- Desktop -->
  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == ''">
    <Content Include="runtimes/win-*/**/*.*;runtimes/linux-*/**/*.*;runtimes/osx-*/**/*.*" Pack="false">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <!-- Apple -->
  <!-- The .xcframework files under `/runtimes/ios` and `/runtimes/maccatalyst` are not interchangeable. -->
  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'ios'">
    <Content Include="runtimes/ios/native/*.xcframework.zip" Pack="false">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'maccatalyst'">
    <Content Include="runtimes/maccatalyst/native/*.xcframework.zip" Pack="false">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <!-- Android -->
  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'android'">
    <AndroidNativeLibrary Include="runtimes/android-arm64/native/libpowersync.so" Abi="arm64-v8a" />
    <AndroidNativeLibrary Include="runtimes/android-x64/native/libpowersync.so" Abi="x86_64" />
    <AndroidNativeLibrary Include="runtimes/android-arm/native/libpowersync.so" Abi="armeabi-v7a" />
    <AndroidNativeLibrary Include="runtimes/android-x86/native/libpowersync.so" Abi="x86" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="../../icon.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
