name: Build Docs

on: push

permissions:
  contents: read

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore docfx
        working-directory: docs
        run: dotnet tool restore

      - name: Restore Projects
        run: |
          dotnet restore PowerSync/PowerSync.Common/PowerSync.Common.csproj -p:TargetFrameworks=net8.0
          dotnet restore PowerSync/PowerSync.Maui/PowerSync.Maui.csproj -p:TargetFrameworks=net8.0

      - name: Generate API Metadata
        working-directory: docs
        run: dotnet docfx metadata docfx.json --warningsAsErrors --noRestore

      - name: Build Docs
        working-directory: docs
        run: dotnet docfx build docfx.json --warningsAsErrors
