# The version is pulled from the CHANGELOG.md file of the package.
# Add a `-dev.xxx` suffix to the version. Example: `0.0.1-dev.1`
name: Create Dev Release

on:
  workflow_dispatch:
  # TODO ALERT ALERT ALERT VERY TEMPORARY TRIGGER ALERT ALERT ALERT DO NOT MERGE THIS ALERT ALERT ALERT
  # GitHub won't allow manual workflow dispatch on a new workflow, so use push as a workaround while testing
  push:
    branches:
      - tmp/code-signing-dev

jobs:
  build:
    name: Build Packages
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install MAUI Workloads
        run: dotnet workload restore

      - name: Download PowerSync extension
        run: dotnet run --project Tools/Setup

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Android SDK for net8.0-android
        run: dotnet build PowerSync/PowerSync.Common -t:InstallAndroidDependencies -f net8.0-android -p:AndroidSdkDirectory="$ANDROID_HOME" -p:AcceptAndroidSdkLicenses=True

      - name: Extract Common Package Version from CHANGELOG.md
        shell: bash
        run: |
          COMMON_VERSION=$(awk '/^## [0-9]+\.[0-9]+\.[0-9]+-dev(\.[0-9]+)?$/ {print $2; exit}' PowerSync/PowerSync.Common/CHANGELOG.md)
          if [[ -z "$COMMON_VERSION" ]]; then
            echo "Error: Invalid dev version found in PowerSync.Common/CHANGELOG.md. Expected format: x.x.x-dev.x"
            exit 1
          fi
          echo "Detected Version: $COMMON_VERSION"
          echo "VERSION=$COMMON_VERSION" >> $GITHUB_ENV

      - name: Run Pack For Common
        run: dotnet pack PowerSync/PowerSync.Common -c Release -o ${{ github.workspace }}/output

      - name: Extract MAUI Package Version from CHANGELOG.md
        shell: bash
        run: |
          MAUI_VERSION=$(awk '/^## [0-9]+\.[0-9]+\.[0-9]+-dev(\.[0-9]+)?$/ {print $2; exit}' PowerSync/PowerSync.Maui/CHANGELOG.md)
          if [[ -z "$MAUI_VERSION" ]]; then
            echo "Error: Invalid dev version found in PowerSync.Maui/CHANGELOG.md. Expected format: x.x.x-dev.x"
            exit 1
          fi
          echo "Detected Version: $MAUI_VERSION"
          echo "VERSION=$MAUI_VERSION" >> $GITHUB_ENV

      - name: Run Pack For MAUI
        run: dotnet pack PowerSync/PowerSync.Maui -c Release -o ${{ github.workspace }}/output

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildArtifacts
          path: ${{ github.workspace }}/output/**/*.nupkg

  sign:
    needs: build
    name: Sign NuGet Artifacts
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: BuildArtifacts
        path: BuildArtifacts
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Sign CLI tool
      run: dotnet tool install --tool-path . --prerelease sign
    
    - name: Azure CLI login
      uses: azure/login@v1
      with:
        allow-no-subscriptions: true
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}

    - name: Sign artifacts
      shell: pwsh
      run: >
        ./sign code azure-key-vault
        **/*.nupkg
        --base-directory "${{ github.workspace }}/BuildArtifacts"
        --publisher-name "PowerSync"
        --description "PowerSync .NET SDK"
        --description-url "https://github.com/powersync-ja/powersync-dotnet"
        --azure-credential-type "azure-cli"
        --azure-key-vault-url "${{ env.KEY_VAULT_URL }}"
        --azure-key-vault-certificate "${{ env.KEY_VAULT_CERTIFICATE_ID }}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SignedArtifacts
        path: BuildArtifacts

  publish:
    needs: [build, sign]
    name: Publish NuGet Packages
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download signed artifacts
        uses: actions/download-artifact@v4
        with:
          name: SignedArtifacts
          path: SignedArtifacts

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Validate artifact signatures
        run: dotnet nuget verify ${{ github.workspace }}/SignedArtifacts/**/*.nupkg

      - name: NuGet Login
        id: login
        uses: NuGet/login@v1
        with:
          user: PowerSync
          
      - name: Run Push For Common
        run: |
          dotnet nuget push ${{ github.workspace }}/SignedArtifacts/PowerSync.Common*.nupkg \
          --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
          --source https://api.nuget.org/v3/index.json

      - name: Run Push For Maui
        run: |
          dotnet nuget push ${{ github.workspace }}/SignedArtifacts/PowerSync.Maui*.nupkg \
          --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
          --source https://api.nuget.org/v3/index.json
