# The version is pulled from the CHANGELOG.md file of the package.
name: Release

on: workflow_dispatch

jobs:
  build:
    name: Build Packages
    runs-on: macos-latest
    environment: production
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read

    outputs:
      common_version: ${{ steps.extract_version.outputs.common_version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install MAUI Workloads
        run: dotnet workload restore

      - name: Download PowerSync extension
        run: dotnet run --project Tools/Setup

      - name: Restore dependencies
        run: dotnet restore

      - name: Install Android SDK for net8.0-android
        run: dotnet build PowerSync/PowerSync.Common -t:InstallAndroidDependencies -f net8.0-android -p:AndroidSdkDirectory="$ANDROID_HOME" -p:AcceptAndroidSdkLicenses=True

      - name: Extract Common Package Version from CHANGELOG.md
        id: extract_version
        shell: bash
        run: |
          COMMON_VERSION=$(awk '/^## [0-9]+\.[0-9]+\.[0-9]+/ {print $2; exit}' PowerSync/PowerSync.Common/CHANGELOG.md)
          if [[ -z "$COMMON_VERSION" ]]; then
            echo "Error: Invalid version found in PowerSync.Common/CHANGELOG.md. Expected format: '## x.x.x'"
            exit 1
          fi
          echo "Detected Version: $COMMON_VERSION"
          echo "VERSION=$COMMON_VERSION" >> $GITHUB_ENV
          echo "common_version=$COMMON_VERSION" >> $GITHUB_OUTPUT

      - name: Run Pack For Common
        run: dotnet pack PowerSync/PowerSync.Common -c Release -o ${{ github.workspace }}/output

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildArtifacts
          path: ${{ github.workspace }}/output/**/*.nupkg

  sign:
    needs: build
    name: Sign NuGet Artifacts
    runs-on: windows-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: BuildArtifacts
          path: BuildArtifacts

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install Sign CLI tool
        run: dotnet tool install --tool-path . --prerelease sign

      - name: Azure CLI login
        uses: azure/login@v1
        with:
          allow-no-subscriptions: true
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}

      - name: Sign artifacts
        shell: pwsh
        run: >
          ./sign code azure-key-vault
          **/*.nupkg
          --base-directory "${{ github.workspace }}/BuildArtifacts"
          --publisher-name "PowerSync"
          --description "PowerSync .NET SDK"
          --description-url "https://github.com/powersync-ja/powersync-dotnet"
          --timestamp-url "http://timestamp.digicert.com"
          --azure-credential-type "azure-cli"
          --azure-key-vault-url "${{ vars.KEY_VAULT_URL }}"
          --azure-key-vault-certificate "${{ vars.KEY_VAULT_CERTIFICATE_ID }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SignedArtifacts
          path: BuildArtifacts

  publish:
    needs: [build, sign]
    name: Publish NuGet Packages
    runs-on: windows-latest
    environment: production

    permissions:
      id-token: write
      contents: write # GitHub releases

    steps:
      - name: Download signed artifacts
        uses: actions/download-artifact@v4
        with:
          name: SignedArtifacts
          path: SignedArtifacts

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Validate artifact signatures
        run: dotnet nuget verify ${{ github.workspace }}/SignedArtifacts/**/*.nupkg

      - name: NuGet Login
        id: login
        uses: NuGet/login@v1
        with:
          user: ${{ vars.NUGET_USERNAME }}

      - name: Run Push For Common
        run: >
          dotnet nuget push "${{ github.workspace }}\SignedArtifacts\PowerSync.Common*.nupkg"
          --api-key "${{ steps.login.outputs.NUGET_API_KEY }}"
          --source https://api.nuget.org/v3/index.json

      - name: Create GitHub Release For Common
        continue-on-error: true
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          COMMON_VERSION: ${{ needs.build.outputs.common_version }}
        run: |
          gh release create "PowerSync.Common@${COMMON_VERSION}" \
            --draft \
            --title "PowerSync.Common@${COMMON_VERSION}" \
            --target main \
            --generate-notes \
            SignedArtifacts/PowerSync.Common*.nupkg

