name: Test Packages

on:
  push:

jobs:
  build:
    strategy:
      matrix: 
        runner: [windows-latest, windows-11-arm]
    name: Test Packages ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0' 

      - name: Install MAUI Workloads
        run: dotnet workload restore
        
      - name: Download PowerSync extension
        run: dotnet run --project Tools/Setup    

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Run tests
        run: dotnet test -v n --framework net8.0